// definitions 
#define rows  5
#define columns 5
// data types 
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;
// prototypes 
void   u8spaces(uint8 location[rows][columns]);
void   u8takeout(uint8 location[rows][columns]);
uint32 u8counter(uint8 location[rows][columns]);
uint32 u8gain(uint8 location[rows][columns]);
void  u8Diagram(uint8 location[rows][columns]);
uint8 intput=0;


